@extends('client.main_index')
@section('index')
<div>
    @include('client.index.main_banner');
    @include('client.index.men_area');
    @include('client.index.women_area');
    @include('client.index.kids_area');
    @include('client.index.explore');
</div>
@endsection